### PR TITLE
Convert garn-bin.js to TypeScript

### LINKED ISSUE #21: garn-bin.js to garn-bin.ts?
I was just about to open a PR with full type coverage in `garn-bin.js` in JSDoc comments. But it's kinda ugly and verbose. Is it perhaps time to convert `garn-bin.js` to `garn-bin.ts` instead? The historic reason for why it's a `.js` file was just because it didn't do a whole lot, and it's important to consider the fact that `garn-bin.js` runs as the entry point and it's not safe to import from/to it for all things.

But I don't think that's a good reason for having it as a `.js` file (anymore). There's also some code duplication between `garn-bin.js` and other files that would be nice to get rid of.

What do you think? I'd be happy to create a PR for it.

### PR DESCRIPTION
**Pull request by andersekdahl**
This converts the file `garn-bin.js` to TypeScript and fixes a number of issues TypeScript told me about along the journey. It was a great ride.

Fixes #21

### CODE REVIEW

**Comment by erik-kallen** [comment]
@lindelleric Any chance to get this merged? After this, we can easily fix #28, which would be a major improvement.

TypeScript 4.5.4 is ancient

**Comment by erik-kallen** [comment]
Or maybe @yoohahn ?

**Comment by yoohahn** [comment]
@erik-kallen I rebased and tested it here https://github.com/yoohahn/garn-template/tree/test-bin-as-ts and it does not work as expected when executing workspaces. From the root's `buildsystem` you should be able to run `workspaces.runTask('WORKSPACE_NAME', 'TASK')`, that does not work. Task in a workspace is also "hoisted" to workspaces, so a task in any workspace should work if running `garn workspace TASK` instead of `garn workspace NAME TASK`, but it don't work.

**Comment by erik-kallen** [comment]
@andersekdahl Any idea?

**Comment by andersekdahl** [comment]
> @erik-kallen I rebased and tested it here https://github.com/yoohahn/garn-template/tree/test-bin-as-ts and it does not work as expected when executing workspaces. From the root's `buildsystem` you should be able to run `workspaces.runTask('WORKSPACE_NAME', 'TASK')`, that does not work. Task in a workspace is also "hoisted" to workspaces, so a task in any workspace should work if running `garn workspace TASK` instead of `garn workspace NAME TASK`, but it don't work.

Are you sure that this PR introduces that bug? Been a long time since I created the PR so I don't quite remember all details, but the changes in the PR doesn't look like it could cause such a behavior change?

**Comment by yoohahn** [comment]
All the commands works as expected from latest code on main when I test there, and it also runs on many projects without any issues.

**Comment by yoohahn** [comment]
@erik-kallen Please have a look at https://github.com/avensia-oss/garn/pull/33 and the rc-version `0.8.0-rc.1`. It has worked in all my cases mention above. Will take a look in some projects tomorrow as well.

**Comment by yoohahn** [comment]
Fixed in https://github.com/avensia-oss/garn/pull/33

**Pull request closed without merging**
