### PR TITLE
Don't assume that .buildcache folder exists

### PR DESCRIPTION
**Pull request by andersekdahl**
This fixes an issue where a clean git checkout doesn't have the `buildsystem/.buildcache` folder and the copy of eg `yarn.lock`  into `buildsystem/.buildcache` fails. This adds a check which creates the folder if it doesn't exist already.

### CODE REVIEW

**Review by lindelleric — APPROVED** [review]
+2 Looks good!

**Comment by lindelleric** [comment]
Released in version 0.4.2.

**Comment by andersekdahl** [comment]
Sweet, thanks! Don't you think it's time to release 1.0.0 btw? Having it as 0.X.X means that every version is considered a major, so 0.4.1 won't be clumped together with 0.4.2 which means you can end up with multiple versions of garn and that just leads to trouble.

**Comment by lindelleric** [comment]
Well, that depends on how strict you define the dependency version range. But yes, I agree that it is time to release version 1.

**Pull request merged**
